targets:
  $default:
    builders:
      code_gen_demo|mark_builder:
        enabled: true

builders:

  user:
    import: "package:flutter_common/Annotations/ServiceGenerator.dart" #导入builder所在包路径
    builder_factories: ["userBuilder"] #返回builder方法名称列表
    build_extensions: {'.dart': ['.user.dart'] } #输入扩展名和输出扩展名的映射
    auto_apply: root_package #仅将此生成器用于顶级软件包，枚举值 none、dependents、all_packages、root_package
    build_to: source #输出进入其主要输入的源树，枚举值 cache、source

  Router:
    import: "package:flutter_common/Annotations/ServiceGenerator.dart"
    builder_factories: ["routerBuilder"]
    build_extensions: {'.dart': ['.rout.dart'] }
    auto_apply: root_package
    runs_before: [':routerCenter'] #用于调整构建顺序
    build_to: cache


  routerCenter:
    import: "package:flutter_common/Annotations/ServiceGenerator.dart"
    builder_factories: ["routerCenterBuilder"]
    build_extensions: {'.dart': ['.mark.dart'] }
    auto_apply: root_package
    build_to: source

  server_entity:
    import: "package:flutter_common/Annotations/ServiceGenerator.dart"
    builder_factories: ["entityBuilder"]
    build_extensions: {".dart": [".enti.dart"]}
    auto_apply: root_package
    build_to: cache
    runs_before: [':apiGenerator']


  #  dio_entity:
  #    import: "package:flutter_common/Annotations/ServiceGenerator.dart"
  #    builder_factories: ["dioBuilder"]
  #    build_extensions: {".dart": [".dio.dart"]}
  #    auto_apply: root_package
  #    build_to: cache
  #    runs_before: [':apiGenerator']

  apiGenerator:
    import: "package:flutter_common/Annotations/ServiceGenerator.dart"
    builder_factories: ["apiBuilder"]
    build_extensions: {".dart": [".serv.dart"]}
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]




